### ISSUE TITLE
Markdown unordered list '-' is being converted to '*'

### ISSUE THREAD

**Issue by peterschussheim** [prettier/prettier-vscode#276]
I noticed today that an unordered list such as:

```markdown
# TODO

- [ ] write simple unit tests for `/transducers`
- [ ] write simple unit tests for `/utilities`
- [ ] Fix unit tests for `/collection`
- [ ] modularize `/transducers` and `/utilities`
```

is now converted to the following format:

```markdown
# TODO

* [ ] write simple unit tests for `/transducers`
* [ ] write simple unit tests for `/utilities`
* [ ] Fix unit tests for `/collection`
* [ ] modularize `/transducers` and `/utilities`
```

I'd like to know why this is happening and how I can prevent this from occurring.

Thank you

**Comment by CiGit** [comment]
Prettier does this. 
see prettier/prettier#3025
